// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"crud-api/internal/domain/user"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserCache creates a new instance of MockUserCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserCache {
	mock := &MockUserCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserCache is an autogenerated mock type for the UserCache type
type MockUserCache struct {
	mock.Mock
}

type MockUserCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserCache) EXPECT() *MockUserCache_Expecter {
	return &MockUserCache_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockUserCache
func (_mock *MockUserCache) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserCache_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserCache_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserCache_Expecter) Delete(ctx interface{}, id interface{}) *MockUserCache_Delete_Call {
	return &MockUserCache_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockUserCache_Delete_Call) Run(run func(ctx context.Context, id string)) *MockUserCache_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserCache_Delete_Call) Return(err error) *MockUserCache_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserCache_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockUserCache_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockUserCache
func (_mock *MockUserCache) Get(ctx context.Context, id string) (*user.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUserCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserCache_Expecter) Get(ctx interface{}, id interface{}) *MockUserCache_Get_Call {
	return &MockUserCache_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockUserCache_Get_Call) Run(run func(ctx context.Context, id string)) *MockUserCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserCache_Get_Call) Return(user1 *user.User, err error) *MockUserCache_Get_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserCache_Get_Call) RunAndReturn(run func(ctx context.Context, id string) (*user.User, error)) *MockUserCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockUserCache
func (_mock *MockUserCache) Set(ctx context.Context, u *user.User, ttl time.Duration) error {
	ret := _mock.Called(ctx, u, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.User, time.Duration) error); ok {
		r0 = returnFunc(ctx, u, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockUserCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - u *user.User
//   - ttl time.Duration
func (_e *MockUserCache_Expecter) Set(ctx interface{}, u interface{}, ttl interface{}) *MockUserCache_Set_Call {
	return &MockUserCache_Set_Call{Call: _e.mock.On("Set", ctx, u, ttl)}
}

func (_c *MockUserCache_Set_Call) Run(run func(ctx context.Context, u *user.User, ttl time.Duration)) *MockUserCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.User
		if args[1] != nil {
			arg1 = args[1].(*user.User)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserCache_Set_Call) Return(err error) *MockUserCache_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserCache_Set_Call) RunAndReturn(run func(ctx context.Context, u *user.User, ttl time.Duration) error) *MockUserCache_Set_Call {
	_c.Call.Return(run)
	return _c
}
